In [1]:
import pandas as pd

/Users/mahiradayal/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pandas/compat/__init__.py:120: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)

In [2]:
df = pd.read_csv("/Users/mahiradayal/masters_project/bank_data/patterns.csv")

In [3]:
df.head()

,placekey,safegraph_place_id,parent_placekey,parent_safegraph_place_id,location_name,street_address,city,region,postal_code,safegraph_brand_ids,...,visitor_daytime_cbgs,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_month_brand,popularity_by_hour,popularity_by_day,device_type
0,222-222@65y-sj9-yd9,sg:01666dfc30a349b68859cdadc4420088,NaN,NaN,Citizens Bank,1 Municipal Plz,Clifton Park,NY,12065,SG_BRAND_f58dee45923c7d70f0bf747fee3f4b97,...,"{""360910624061"":4,""360910624032"":4,""3609106250...","{""US"":49}",7338.0,6.0,"{""<5"":6,""5-10"":53,""11-20"":2,""21-60"":4,""61-120""...","{""Planet Fitness"":49,""Stewart's Shops"":25,""Pan...","{""Stewart's Shops"":68,""Shoppers World"":47,""McD...","[0,0,0,0,0,0,0,0,3,6,11,13,12,6,9,11,3,5,2,0,0...","{""Monday"":8,""Tuesday"":10,""Wednesday"":8,""Thursd...","{""android"":20,""ios"":29}"
1,222-222@63q-r6s-hbk,sg:86f6bcbe916446579f45c820b7fd7795,NaN,NaN,Bath National Bank,7434 Seneca Rd N,Hornell,NY,14843,NaN,...,"{""361019606003"":4,""361019607003"":4,""3601501080...","{""US"":38}",5449.0,7.0,"{""<5"":7,""5-10"":38,""11-20"":3,""21-60"":8,""61-120""...","{""Advance Auto Parts"":66,""Mobil"":33,""Subway"":24}","{""Wegmans Food Markets"":67,""Kwik Fill"":57,""Wal...","[0,0,0,0,0,0,0,0,4,8,13,9,16,13,10,18,8,4,5,1,...","{""Monday"":11,""Tuesday"":3,""Wednesday"":7,""Thursd...","{""android"":17,""ios"":21}"
2,22j-222@627-tdt-m49,sg:86f2e03fbf81414d91aae9bae28ed5cc,NaN,NaN,Roslyn Savings Bank,160 S Main St,Freeport,NY,11520,NaN,...,"{""360594143011"":4,""360594143041"":4}","{""US"":4}",NaN,196.0,"{""<5"":0,""5-10"":3,""11-20"":0,""21-60"":0,""61-120"":...","{""BJ's Wholesale Club"":100,""Jersey Mike's"":100}","{""CVS"":95,""Sunoco"":72,""Dunkin'"":71,""Subway"":68...","[0,0,0,0,0,0,0,0,4,5,5,5,3,1,2,1,1,0,0,0,0,0,0,0]","{""Monday"":2,""Tuesday"":2,""Wednesday"":1,""Thursda...","{""android"":4,""ios"":0}"
3,228-222@65z-jqt-4jv,sg:1497683ee48c478daf1418dafb1bdf74,NaN,NaN,Community Bank,104 S Peterboro St,Canastota,NY,13032,SG_BRAND_4bc55c30e696d18d0a971b7a84aa2ea2,...,"{""360530303002"":6,""360530302002"":6,""3605303010...","{""US"":22}",7308.0,6.0,"{""<5"":4,""5-10"":23,""11-20"":1,""21-60"":0,""61-120""...","{""Cellular Sales"":50}","{""SavOn"":71,""Walmart"":58,""McDonald's"":52,""Dunk...","[0,0,0,0,0,0,0,0,2,3,4,5,5,5,3,2,1,0,0,0,0,0,0,0]","{""Monday"":8,""Tuesday"":2,""Wednesday"":4,""Thursda...","{""android"":10,""ios"":9}"
4,zzy-226@627-wc7-9pv,sg:4dc3d15e657b4c7c8badd08e31692f82,NaN,NaN,TD Bank,254 Canal Street Canal & Lafayette,New York,NY,10013,SG_BRAND_a270529277e11434ce7a40cff6c21217,...,"{""420770067013"":4,""340170041013"":4,""4210103840...","{""US"":49}",13053.0,13.5,"{""<5"":1,""5-10"":27,""11-20"":12,""21-60"":14,""61-12...","{""Exxon Mobil"":24,""Duane Reade by Walgreens"":20}","{""Starbucks"":34,""Dunkin'"":28,""McDonald's"":22,""...","[0,0,0,0,0,0,0,1,3,5,8,13,15,11,12,12,11,8,5,2...","{""Monday"":8,""Tuesday"":10,""Wednesday"":6,""Thursd...","{""android"":24,""ios"":28}"

### Using the Google Maps API to generate coordinates for street addresses of banks in New York State

1. I first installed googlemaps and then used concat to put my address columns together to create a single, useable address. 
2. I generated and added in new columns for lat and long, inserting 00 where the API didn't recognize a location. There were few, which I chose to drop from my dataset.

In [4]:
pip install -U googlemaps

Requirement already satisfied: googlemaps in /Users/mahiradayal/.pyenv/versions/3.8.2/lib/python3.8/site-packages (4.4.5)
Requirement already satisfied: requests<3.0,>=2.20.0 in /Users/mahiradayal/.pyenv/versions/3.8.2/lib/python3.8/site-packages (from googlemaps) (2.24.0)
Requirement already satisfied: idna<3,>=2.5 in /Users/mahiradayal/.pyenv/versions/3.8.2/lib/python3.8/site-packages (from requests<3.0,>=2.20.0->googlemaps) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /Users/mahiradayal/.pyenv/versions/3.8.2/lib/python3.8/site-packages (from requests<3.0,>=2.20.0->googlemaps) (2020.6.20)
Requirement already satisfied: chardet<4,>=3.0.2 in /Users/mahiradayal/.pyenv/versions/3.8.2/lib/python3.8/site-packages (from requests<3.0,>=2.20.0->googlemaps) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/mahiradayal/.pyenv/versions/3.8.2/lib/python3.8/site-packages (from requests<3.0,>=2.20.0->googlemaps) (1.25.11)
WARNING: You are using pip version 20.3; however, version 21.1.1 is available.
You should consider upgrading via the '/Users/mahiradayal/.pyenv/versions/3.8.2/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [5]:
import googlemaps
from datetime import datetime

gmaps = googlemaps.Client(key='AIzaSyCyKn8jrgRCFeAPvBxt8aFOi_vPFWKFwHs')

In [6]:
# geocode_result = gmaps.geocode('1600 Amphitheatre Parkway, Mountain View, CA')

In [7]:
df['postal_code'] = df['postal_code'].apply(str)

# Concat address columns together

df['address'] = df['street_address'].str.cat(
    df['city'],sep=", ").str.cat(
    df['region'],sep=", ").str.cat(
    df['postal_code'],sep=", ")

In [8]:
df.head()

,placekey,safegraph_place_id,parent_placekey,parent_safegraph_place_id,location_name,street_address,city,region,postal_code,safegraph_brand_ids,...,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_month_brand,popularity_by_hour,popularity_by_day,device_type,address
0,222-222@65y-sj9-yd9,sg:01666dfc30a349b68859cdadc4420088,NaN,NaN,Citizens Bank,1 Municipal Plz,Clifton Park,NY,12065,SG_BRAND_f58dee45923c7d70f0bf747fee3f4b97,...,"{""US"":49}",7338.0,6.0,"{""<5"":6,""5-10"":53,""11-20"":2,""21-60"":4,""61-120""...","{""Planet Fitness"":49,""Stewart's Shops"":25,""Pan...","{""Stewart's Shops"":68,""Shoppers World"":47,""McD...","[0,0,0,0,0,0,0,0,3,6,11,13,12,6,9,11,3,5,2,0,0...","{""Monday"":8,""Tuesday"":10,""Wednesday"":8,""Thursd...","{""android"":20,""ios"":29}","1 Municipal Plz, Clifton Park, NY, 12065"
1,222-222@63q-r6s-hbk,sg:86f6bcbe916446579f45c820b7fd7795,NaN,NaN,Bath National Bank,7434 Seneca Rd N,Hornell,NY,14843,NaN,...,"{""US"":38}",5449.0,7.0,"{""<5"":7,""5-10"":38,""11-20"":3,""21-60"":8,""61-120""...","{""Advance Auto Parts"":66,""Mobil"":33,""Subway"":24}","{""Wegmans Food Markets"":67,""Kwik Fill"":57,""Wal...","[0,0,0,0,0,0,0,0,4,8,13,9,16,13,10,18,8,4,5,1,...","{""Monday"":11,""Tuesday"":3,""Wednesday"":7,""Thursd...","{""android"":17,""ios"":21}","7434 Seneca Rd N, Hornell, NY, 14843"
2,22j-222@627-tdt-m49,sg:86f2e03fbf81414d91aae9bae28ed5cc,NaN,NaN,Roslyn Savings Bank,160 S Main St,Freeport,NY,11520,NaN,...,"{""US"":4}",NaN,196.0,"{""<5"":0,""5-10"":3,""11-20"":0,""21-60"":0,""61-120"":...","{""BJ's Wholesale Club"":100,""Jersey Mike's"":100}","{""CVS"":95,""Sunoco"":72,""Dunkin'"":71,""Subway"":68...","[0,0,0,0,0,0,0,0,4,5,5,5,3,1,2,1,1,0,0,0,0,0,0,0]","{""Monday"":2,""Tuesday"":2,""Wednesday"":1,""Thursda...","{""android"":4,""ios"":0}","160 S Main St, Freeport, NY, 11520"
3,228-222@65z-jqt-4jv,sg:1497683ee48c478daf1418dafb1bdf74,NaN,NaN,Community Bank,104 S Peterboro St,Canastota,NY,13032,SG_BRAND_4bc55c30e696d18d0a971b7a84aa2ea2,...,"{""US"":22}",7308.0,6.0,"{""<5"":4,""5-10"":23,""11-20"":1,""21-60"":0,""61-120""...","{""Cellular Sales"":50}","{""SavOn"":71,""Walmart"":58,""McDonald's"":52,""Dunk...","[0,0,0,0,0,0,0,0,2,3,4,5,5,5,3,2,1,0,0,0,0,0,0,0]","{""Monday"":8,""Tuesday"":2,""Wednesday"":4,""Thursda...","{""android"":10,""ios"":9}","104 S Peterboro St, Canastota, NY, 13032"
4,zzy-226@627-wc7-9pv,sg:4dc3d15e657b4c7c8badd08e31692f82,NaN,NaN,TD Bank,254 Canal Street Canal & Lafayette,New York,NY,10013,SG_BRAND_a270529277e11434ce7a40cff6c21217,...,"{""US"":49}",13053.0,13.5,"{""<5"":1,""5-10"":27,""11-20"":12,""21-60"":14,""61-12...","{""Exxon Mobil"":24,""Duane Reade by Walgreens"":20}","{""Starbucks"":34,""Dunkin'"":28,""McDonald's"":22,""...","[0,0,0,0,0,0,0,1,3,5,8,13,15,11,12,12,11,8,5,2...","{""Monday"":8,""Tuesday"":10,""Wednesday"":6,""Thursd...","{""android"":24,""ios"":28}","254 Canal Street Canal & Lafayette, New York, ..."

In [9]:
# Just latitutde and longitude, not the whole JSON

latitude = []
longitude = []

def geocode_address(loc):
    gmaps = googlemaps.Client(key='AIzaSyCyKn8jrgRCFeAPvBxt8aFOi_vPFWKFwHs')
    geocode_result = gmaps.geocode(loc)
    if len(geocode_result) > 0: 
        lat = geocode_result[0]["geometry"]["location"]["lat"]
        lon = geocode_result[0]["geometry"]["location"]["lng"]
        latitude.append(lat)
        longitude.append(lon)
    else: 
        lat = '00'
        lon = '00'
        latitude.append(lat)
        longitude.append(lon)
    #test - print results
    # print (lat,lon)

In [10]:
# To test: 
short = df.head(3)
short.shape

(3, 29)

In [11]:
# NEVER RUN THIS AGAIN IT TAKES FOREVER. USE MY NEW DF FROM CSV. 
# for addresses in df.address:
#     geocode_address(addresses)

In [12]:
# df['lats'] = latitude
# df['longs'] = longitude

In [13]:
df.head()

,placekey,safegraph_place_id,parent_placekey,parent_safegraph_place_id,location_name,street_address,city,region,postal_code,safegraph_brand_ids,...,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_month_brand,popularity_by_hour,popularity_by_day,device_type,address,lats,longs
0,222-222@65y-sj9-yd9,sg:01666dfc30a349b68859cdadc4420088,NaN,NaN,Citizens Bank,1 Municipal Plz,Clifton Park,NY,12065,SG_BRAND_f58dee45923c7d70f0bf747fee3f4b97,...,6.0,"{""<5"":6,""5-10"":53,""11-20"":2,""21-60"":4,""61-120""...","{""Planet Fitness"":49,""Stewart's Shops"":25,""Pan...","{""Stewart's Shops"":68,""Shoppers World"":47,""McD...","[0,0,0,0,0,0,0,0,3,6,11,13,12,6,9,11,3,5,2,0,0...","{""Monday"":8,""Tuesday"":10,""Wednesday"":8,""Thursd...","{""android"":20,""ios"":29}","1 Municipal Plz, Clifton Park, NY, 12065",42.8636,-73.7861
1,222-222@63q-r6s-hbk,sg:86f6bcbe916446579f45c820b7fd7795,NaN,NaN,Bath National Bank,7434 Seneca Rd N,Hornell,NY,14843,NaN,...,7.0,"{""<5"":7,""5-10"":38,""11-20"":3,""21-60"":8,""61-120""...","{""Advance Auto Parts"":66,""Mobil"":33,""Subway"":24}","{""Wegmans Food Markets"":67,""Kwik Fill"":57,""Wal...","[0,0,0,0,0,0,0,0,4,8,13,9,16,13,10,18,8,4,5,1,...","{""Monday"":11,""Tuesday"":3,""Wednesday"":7,""Thursd...","{""android"":17,""ios"":21}","7434 Seneca Rd N, Hornell, NY, 14843",42.3618,-77.6647
2,22j-222@627-tdt-m49,sg:86f2e03fbf81414d91aae9bae28ed5cc,NaN,NaN,Roslyn Savings Bank,160 S Main St,Freeport,NY,11520,NaN,...,196.0,"{""<5"":0,""5-10"":3,""11-20"":0,""21-60"":0,""61-120"":...","{""BJ's Wholesale Club"":100,""Jersey Mike's"":100}","{""CVS"":95,""Sunoco"":72,""Dunkin'"":71,""Subway"":68...","[0,0,0,0,0,0,0,0,4,5,5,5,3,1,2,1,1,0,0,0,0,0,0,0]","{""Monday"":2,""Tuesday"":2,""Wednesday"":1,""Thursda...","{""android"":4,""ios"":0}","160 S Main St, Freeport, NY, 11520",40.653,-73.5784
3,228-222@65z-jqt-4jv,sg:1497683ee48c478daf1418dafb1bdf74,NaN,NaN,Community Bank,104 S Peterboro St,Canastota,NY,13032,SG_BRAND_4bc55c30e696d18d0a971b7a84aa2ea2,...,6.0,"{""<5"":4,""5-10"":23,""11-20"":1,""21-60"":0,""61-120""...","{""Cellular Sales"":50}","{""SavOn"":71,""Walmart"":58,""McDonald's"":52,""Dunk...","[0,0,0,0,0,0,0,0,2,3,4,5,5,5,3,2,1,0,0,0,0,0,0,0]","{""Monday"":8,""Tuesday"":2,""Wednesday"":4,""Thursda...","{""android"":10,""ios"":9}","104 S Peterboro St, Canastota, NY, 13032",43.0789,-75.751
4,zzy-226@627-wc7-9pv,sg:4dc3d15e657b4c7c8badd08e31692f82,NaN,NaN,TD Bank,254 Canal Street Canal & Lafayette,New York,NY,10013,SG_BRAND_a270529277e11434ce7a40cff6c21217,...,13.5,"{""<5"":1,""5-10"":27,""11-20"":12,""21-60"":14,""61-12...","{""Exxon Mobil"":24,""Duane Reade by Walgreens"":20}","{""Starbucks"":34,""Dunkin'"":28,""McDonald's"":22,""...","[0,0,0,0,0,0,0,1,3,5,8,13,15,11,12,12,11,8,5,2...","{""Monday"":8,""Tuesday"":10,""Wednesday"":6,""Thursd...","{""android"":24,""ios"":28}","254 Canal Street Canal & Lafayette, New York, ...",40.7185,-74.0008

In [14]:
df.shape

(2686, 31)

In [15]:
df[df.lats == '00'].drop

<bound method DataFrame.drop of                 placekey                   safegraph_place_id parent_placekey  \
950  zzy-222@662-6gg-gkz  sg:b6e71adce84d41bb95a5c189e0443db2             NaN

    parent_safegraph_place_id      location_name street_address        city  \
950                       NaN  Community Bank Na      La Grasse  Ogdensburg

    region postal_code safegraph_brand_ids  ... median_dwell  \
950     NY       13694                 NaN  ...         13.0

                                  bucketed_dwell_times related_same_day_brand  \
950  {"<5":5,"5-10":21,"11-20":4,"21-60":6,"61-120"...        {"NBT Bank":25}

                              related_same_month_brand  \
950  {"Sunoco":63,"Walmart":48,"Community Bank":46,...

                                    popularity_by_hour  \
950  [2,2,2,2,2,2,2,9,10,13,14,15,16,12,13,10,12,3,...

                                     popularity_by_day  \
950  {"Monday":9,"Tuesday":7,"Wednesday":3,"Thursda...

                 device_type                           address lats longs
950  {"android":14,"ios":18}  La Grasse, Ogdensburg, NY, 13694   00    00

[1 rows x 31 columns]>

In [16]:
df = df[df.lats != '00']

In [17]:
df['lats'] = df['lats'].apply(str)
df['longs'] = df['longs'].apply(str)

df['coordinates'] = df['lats'].str.cat(
    df['longs'],sep=", ")

### Visitor home CBGS
These CBGs show the census block groups visitors originated from, which is important for me to understand how far people travel in banking deserts to reach the closest bank. The data is hard to use because of formatting: As seen below, each cell contains multiple CBGs, the number of visitors from each CBG separated by commas. 

I'm working on creating a useful way to clean this data to use it for analysis â€”Â I considered splitting by "," which is ineffective because it creates new columns for each unique CBG. This makes it hard to count and compare in a full dataset. It split up to 11 columns for some and only 1 or 2 for others.

In [18]:
df.visitor_home_cbgs

0       {"361150930002":5,"360910621001":4,"3608305200...
1       {"361019606001":5,"361019610002":4,"3610196050...
2                                                      {}
3       {"360530301011":5,"360530301031":5,"3605303020...
4       {"131210116101":6,"360470419003":4,"3600502180...
                              ...
2681    {"360610026022":4,"360610061001":4,"3606100820...
2682    {"360550137024":4,"360550131013":4,"3605500580...
2683    {"360850170082":8,"360850128042":6,"3608502770...
2684                                   {"090010108003":4}
2685                                                   {}
Name: visitor_home_cbgs, Length: 2685, dtype: object

In [21]:
# df.columns =['cbg1', 'cbg2', 'Age', 'Weight']
# df['0'] = df['0'].str.replace(r'\D', '').astype(int)

In [22]:
# compression_opts = dict(method='zip',
#                         archive_name='bankscoords.csv')  
# df.to_csv('bankscoords.zip', index=False,
#           compression=compression_opts)

In [23]:
df = pd.read_csv('/Users/mahiradayal/masters_project/bankscoords 2.csv')

In [24]:
df.head()

,placekey,safegraph_place_id,parent_placekey,parent_safegraph_place_id,location_name,street_address,city,region,postal_code,safegraph_brand_ids,...,bucketed_dwell_times,related_same_day_brand,related_same_month_brand,popularity_by_hour,popularity_by_day,device_type,address,lats,longs,coordinates
0,222-222@65y-sj9-yd9,sg:01666dfc30a349b68859cdadc4420088,NaN,NaN,Citizens Bank,1 Municipal Plz,Clifton Park,NY,12065,SG_BRAND_f58dee45923c7d70f0bf747fee3f4b97,...,"{""<5"":6,""5-10"":53,""11-20"":2,""21-60"":4,""61-120""...","{""Planet Fitness"":49,""Stewart's Shops"":25,""Pan...","{""Stewart's Shops"":68,""Shoppers World"":47,""McD...","[0,0,0,0,0,0,0,0,3,6,11,13,12,6,9,11,3,5,2,0,0...","{""Monday"":8,""Tuesday"":10,""Wednesday"":8,""Thursd...","{""android"":20,""ios"":29}","1 Municipal Plz, Clifton Park, NY, 12065",42.863625,-73.786142,"42.8636245, -73.7861422"
1,222-222@63q-r6s-hbk,sg:86f6bcbe916446579f45c820b7fd7795,NaN,NaN,Bath National Bank,7434 Seneca Rd N,Hornell,NY,14843,NaN,...,"{""<5"":7,""5-10"":38,""11-20"":3,""21-60"":8,""61-120""...","{""Advance Auto Parts"":66,""Mobil"":33,""Subway"":24}","{""Wegmans Food Markets"":67,""Kwik Fill"":57,""Wal...","[0,0,0,0,0,0,0,0,4,8,13,9,16,13,10,18,8,4,5,1,...","{""Monday"":11,""Tuesday"":3,""Wednesday"":7,""Thursd...","{""android"":17,""ios"":21}","7434 Seneca Rd N, Hornell, NY, 14843",42.361763,-77.664681,"42.3617634, -77.6646805"
2,22j-222@627-tdt-m49,sg:86f2e03fbf81414d91aae9bae28ed5cc,NaN,NaN,Roslyn Savings Bank,160 S Main St,Freeport,NY,11520,NaN,...,"{""<5"":0,""5-10"":3,""11-20"":0,""21-60"":0,""61-120"":...","{""BJ's Wholesale Club"":100,""Jersey Mike's"":100}","{""CVS"":95,""Sunoco"":72,""Dunkin'"":71,""Subway"":68...","[0,0,0,0,0,0,0,0,4,5,5,5,3,1,2,1,1,0,0,0,0,0,0,0]","{""Monday"":2,""Tuesday"":2,""Wednesday"":1,""Thursda...","{""android"":4,""ios"":0}","160 S Main St, Freeport, NY, 11520",40.653044,-73.578437,"40.653044, -73.57843729999999"
3,228-222@65z-jqt-4jv,sg:1497683ee48c478daf1418dafb1bdf74,NaN,NaN,Community Bank,104 S Peterboro St,Canastota,NY,13032,SG_BRAND_4bc55c30e696d18d0a971b7a84aa2ea2,...,"{""<5"":4,""5-10"":23,""11-20"":1,""21-60"":0,""61-120""...","{""Cellular Sales"":50}","{""SavOn"":71,""Walmart"":58,""McDonald's"":52,""Dunk...","[0,0,0,0,0,0,0,0,2,3,4,5,5,5,3,2,1,0,0,0,0,0,0,0]","{""Monday"":8,""Tuesday"":2,""Wednesday"":4,""Thursda...","{""android"":10,""ios"":9}","104 S Peterboro St, Canastota, NY, 13032",43.078948,-75.751004,"43.0789479, -75.75100359999999"
4,zzy-226@627-wc7-9pv,sg:4dc3d15e657b4c7c8badd08e31692f82,NaN,NaN,TD Bank,254 Canal Street Canal & Lafayette,New York,NY,10013,SG_BRAND_a270529277e11434ce7a40cff6c21217,...,"{""<5"":1,""5-10"":27,""11-20"":12,""21-60"":14,""61-12...","{""Exxon Mobil"":24,""Duane Reade by Walgreens"":20}","{""Starbucks"":34,""Dunkin'"":28,""McDonald's"":22,""...","[0,0,0,0,0,0,0,1,3,5,8,13,15,11,12,12,11,8,5,2...","{""Monday"":8,""Tuesday"":10,""Wednesday"":6,""Thursd...","{""android"":24,""ios"":28}","254 Canal Street Canal & Lafayette, New York, ...",40.718453,-74.000844,"40.7184528, -74.0008438"

In [42]:
# I want to look at what all my CBGs are 

cbg = df[["visitor_home_cbgs", "coordinates"]].head(5)
# cbg.visitor_home_cbgs.explode()
cbg.head()

,visitor_home_cbgs,coordinates
0,"{""361150930002"":5,""360910621001"":4,""3608305200...","42.8636245, -73.7861422"
1,"{""361019606001"":5,""361019610002"":4,""3610196050...","42.3617634, -77.6646805"
2,{},"40.653044, -73.57843729999999"
3,"{""360530301011"":5,""360530301031"":5,""3605303020...","43.0789479, -75.75100359999999"
4,"{""131210116101"":6,""360470419003"":4,""3600502180...","40.7184528, -74.0008438"

In [87]:
split_cbg = []
split = cbg.visitor_home_cbgs.str.split(",", expand=True)
split_cbg.append(split)

In [88]:
split['visitor_home'] = cbg.visitor_home_cbgs
split['location'] = cbg.coordinates

In [92]:
split.index.rename('0','cbg1')

In [94]:
split.columns

# idx = pd.Index(['A', 'C', 'A', 'B'], name='score')
# idx.rename('grade')

Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 'visitor_home', 'location'], dtype='object')